-- Baseline schema, matching the JPA entities as of the Flyway introduction.
-- Existing environments are baselined onto this version (see spring.flyway.baseline-*
-- in application.properties) rather than re-running this script against their already-existing tables.
-- Fresh environments (new dev setups, CI) run this script to bootstrap the schema from empty.

create table roles (id integer generated by default as identity, name varchar(50) not null unique, primary key (id));
create index idx_role_name on roles (name);

create table users (id integer generated by default as identity, role_id integer not null, token_version integer not null, created_at timestamp(6) not null, email varchar(100) not null unique, name varchar(100) not null, profile_picture varchar(500), description text, password varchar(255) not null, primary key (id));
create index idx_user_email on users (email);
create index idx_user_role on users (role_id);
alter table users add constraint fk_users_role foreign key (role_id) references roles;

create table categories (id integer generated by default as identity, created_at timestamp(6) not null, name varchar(100) not null unique, slug varchar(150) not null unique, primary key (id));

create table posts (category_id integer not null, id integer generated by default as identity, moderated_by integer, rejection_count integer not null, user_id integer not null, created_at timestamp(6) not null, moderated_at timestamp(6), published_at timestamp(6), updated_at timestamp(6) not null, title varchar(200) not null, slug varchar(250) not null unique, cover_image varchar(500), moderation_note varchar(500), content text, status varchar(20) not null, primary key (id));
alter table posts add constraint fk_posts_user foreign key (user_id) references users;
alter table posts add constraint fk_posts_category foreign key (category_id) references categories;
alter table posts add constraint fk_posts_moderated_by foreign key (moderated_by) references users;

create table refresh_tokens (user_id integer not null, created_at timestamp(6) not null, expires_at timestamp(6) not null, id bigint generated by default as identity, token varchar(64) not null unique, primary key (id));
create index idx_refresh_tokens_token on refresh_tokens (token);
create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
alter table refresh_tokens add constraint fk_refresh_tokens_user foreign key (user_id) references users;

create table author_requests (id integer generated by default as identity, requester_id integer not null, resolved_by_id integer, created_at timestamp(6) not null, resolved_at timestamp(6), admin_note varchar(500), motivation varchar(1000), status varchar(20) not null, primary key (id));
create index idx_author_request_requester_status on author_requests (requester_id, status);
create index idx_author_request_status_created on author_requests (status, created_at);
alter table author_requests add constraint fk_author_requests_requester foreign key (requester_id) references users;
alter table author_requests add constraint fk_author_requests_resolved_by foreign key (resolved_by_id) references users;

create table admin_action_logs (admin_id integer not null, id integer generated by default as identity, target_id integer not null, created_at timestamp(6) not null, action_type varchar(50) not null, target_type varchar(50) not null, details varchar(1000), admin_email varchar(255) not null, primary key (id));
create index idx_admin_action_log_admin_id on admin_action_logs (admin_id);
create index idx_admin_action_log_target on admin_action_logs (target_type, target_id);
create index idx_admin_action_log_created_at on admin_action_logs (created_at);
