-- Email verification on registration.
-- email_verified defaults to false for new rows; existing accounts predate
-- verification and are backfilled as verified so they are not locked out.
alter table users add column email_verified boolean not null default false;
update users set email_verified = true;

-- Single-use verification tokens, stored as SHA-256 hashes (same pattern as refresh_tokens).
-- Superseded tokens are expired (expires_at = now) rather than deleted so the resend
-- cooldown and daily cap can be computed from created_at; a scheduled job purges old rows.
create table email_verification_tokens (user_id integer not null, created_at timestamp(6) not null, expires_at timestamp(6) not null, id bigint generated by default as identity, token varchar(64) not null unique, primary key (id));
create index idx_email_verification_tokens_token on email_verification_tokens (token);
create index idx_email_verification_tokens_user_id on email_verification_tokens (user_id);
alter table email_verification_tokens add constraint fk_email_verification_tokens_user foreign key (user_id) references users;
